server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # PUBLIC API - PRODUCT
        - id: product-public
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/public/**,/api/categories/public/**,/api/discounts/public/**
          filters:
            - StripPrefix=1

        # AUTH API - PRODUCT
        - id: product-auth
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/auth/**,/api/categories/auth/**,/api/discounts/auth/**
          filters:
            - StripPrefix=1

        # AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/addresses/**,/api/user/**,/api/auth/**
          filters:
            - StripPrefix=1

        # CART SERVICE
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1

        # ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        # PAYMENT SERVICE
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

        # IMAGE SEARCH (Python service)
        - id: image-search-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/image-search/**
          filters:
            - StripPrefix=1

        # EUREKA UI
        - id: eureka-ui
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowed-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
            allowed-headers: [ "*" ]
            exposed-headers: [ "*" ]
            allow-credentials: true